version: '3'
services:
  dns-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-dns-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_dns_api:/usr/lib/python3.6/site-packages/vlab_dns_api
    command: ["python3", "app.py"]

  dns-worker:
    image:
      willnx/vlab-dns-worker
    volumes:
      - ./vlab_dns_api:/usr/lib/python3.6/site-packages/vlab_dns_api
      - /mnt/raid/images/dns:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  dns-broker:
    image:
      rabbitmq:3.7-alpine
